const express = require('express')
const router = express.Router()
const path = require('path')

router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'accessibility-statement', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'next-steps-for-this-report', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'sitemap', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'compliant-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'very-high-risk-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'high-risk-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'medium-risk-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'low-risk-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'unknown-risk-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'sunsetting-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'legacy-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'critical-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'citizen-facing-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'staff-facing-services', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'filters', 'no-plans-for-compliance', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'overview', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'directorate', 'routes')))
router.use(require(path.resolve('src', 'templates', 'report', 'pages', 'pdu', 'routes')))

module.exports = router
